# Create the App Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvjp-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvjp
  template:
    metadata:
      labels:
        app: cvjp
    spec:
      containers:
        - name: cvjp
          image: prengineer/cvjp:latest
          resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"
          ports:
            - name: httpport
              containerPort: 80

---

# Create the Exposed App Service

apiVersion: v1
kind: Service
metadata:
  name: cvjp-external-service
  namespace: production
spec:
  selector:
    app: cvjp
  type: LoadBalancer
  ports:
  - name: httpport
    protocol: TCP
    port: 8001
    targetPort: 80
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.80